### PR TITLE
Adding circular economy link types

### PR DESCRIPTION
**Pull request by philarcher**

### CODE REVIEW

**Review by mgh128 — COMMENTED** [review]
Thanks for adding these.  Will you add the JSON-LD equivalent or should I?
I noticed at line 8824 extra spaces in the rdfs:comment before the word 'link' - so you might have a bouncy spacebar like mine.

**Comment by philarcher** [comment]
I'm working on the JSON-LD now. The file size seems too big for RDF Appspot, I may have to do this manually, so if you can do it properly, so to speak, so much the better. I'll sort out the bouncy space bar!

**Comment by philarcher** [comment]
OK, @mgh128, I've added the circular economy link types to the JSON-LD as well. If you could please review the new entries and, if satisfied, merge them in. 

Thank you

**Comment by mgh128** [comment]
OK.  I'll do the JSON-LD part later this evening. Should only take a couple of minutes.

**Comment by philarcher** [comment]
I've done the JSON-LD  and, as part of that and in response to Issue #4 , I've made defaultLink* defaultLink%2A in the Turtle. The JSON-LD seems perfectly OK with defaultLink* (according to the playground). If you're happy with this @mgh128, please hit the merge button!

**Pull request merged**
